name: Deploy to VPS
env:
  SERVER_NAME: ${{ vars.SERVER_NAME }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        env:
          SERVER_NAME: ${{ env.SERVER_NAME }}
        run: |
          ssh -o StrictHostKeyChecking=no root@151.115.77.139 << EOF
          export SERVER_NAME="${SERVER_NAME}""
          echo "SERVER_NAME on remote : \$SERVER_NAME" 1>&2
          cd /opt/next-dockerize
          git pull origin main
          docker compose pull
          SERVER_NAME=\$SERVER_NAME docker compose -f compose.production.yaml up -d --build
          EOF